name: PDF
on: [push,pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            latexmk -pdf PICCOLLECTION.tex
            latexmk -pdf NM.tex
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: NM.pdf
          asset_name: NM.pdf
          tag: latest
          overwrite: true
